### ISSUE TITLE
Long error

### ISSUE THREAD

**Issue by RubyBoo4life** [WesternGamer/RDR2AudioTool#4]
When i use the audio tool to replace sounds in awc files, when i click replace and select my audio file (.wav) it gives me a long error (error on the picture)
![image](https://github.com/WesternGamer/RDR2AudioTool/assets/88154186/7b76a644-e744-49c1-b979-83074c1fced7)

**Comment by WesternGamer** [comment]
This issue should be fixed in the 0.4.0 release when it comes out.

**Comment by Keegankraft** [comment]
Great, since somehow this fucking bug isnt fixed like 6 months later and im wondering how the fuck oakous praiseaidan and a couple others have managed to get past this bug

**Comment by WesternGamer** [comment]
Just to update anyone who is subscribed to this issue, RDR2 Audio Tool will be updated sometime in the future. The entire program will be rebuilt from the ground up. Due to my schedule being busy, this will not happen in the near future. 

Note that any current issues will be closed when the new update is posted, as the code will be entirely different.
